import csv

# Load the CSV file generated by your Scrapy spider
def load_links_from_csv(csv_file):
    with open(csv_file, "r") as csvfile:
        reader = csv.reader(csvfile)
        links = [row[0] for row in reader]
    return links

# Search for links containing a specific country name
def search_links_by_country(links, country_name):
    matching_links = [link for link in links if country_name.lower() in link.lower()]
    return matching_links

if __name__ == "__main__":
    # Load links from the CSV file
    csv_file = r"C:\Users\user\OneDrive\Desktop\Linksearch\Linktool\document_links.csv"
    links = load_links_from_csv(csv_file)

    # Prompt the user for a country name to search for
    while True:
        country_name = input("Enter a country name to search for (or 'quit' to exit): ")
        if country_name.lower() == "quit":
            break

        # Search for links containing the specified country name
        matching_links = search_links_by_country(links, country_name)

        if matching_links:
            print(f"Links containing '{country_name}':")
            for link in matching_links:
                print(link)
        else:
            print(f"No links containing '{country_name}' found.")
